[module]

[module.hugoVersion]
extended = true
min = "0.78.0"

[[module.imports]]
path = "github.com/aFarkas/lazysizes"
disabled = false

[[module.imports.mounts]]
source = "lazysizes-umd.js"
target = "assets/libs/lazysizes/lazysizes-umd.js"

[[module.imports.mounts]]
source = "plugins"
target = "assets/libs/lazysizes/plugins"


